# Generated by Django 5.0.7 on 2024-08-04 09:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='save_authors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='save_book', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
    ]
